# Generated by Django 3.1.3 on 2023-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230402_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_text',
        ),
    ]
